import { NgModule } from '@angular/core';
import {FlexModule } from '@angular/flex-layout';

import {
  MatInputModule,
  MatCardModule,
  MatButtonModule,
  MatSidenavModule,
  MatListModule,
  MatIconModule,
  MatToolbarModule,
  MatProgressSpinnerModule,
  MatDialogModule,
  MatGridListModule,
  MatMenuModule,
  MatBadgeModule,
  MatTableModule,
  MatTabsModule,
} from '@angular/material';

@NgModule({
  imports: [
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatIconModule,
    MatGridListModule,
    MatMenuModule,
    MatSidenavModule,
    MatBadgeModule,
    FlexModule,
    MatTableModule,
    MatTabsModule,
  ],
  exports: [
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatIconModule,
    MatGridListModule,
    MatMenuModule,
    MatSidenavModule,
    MatBadgeModule,
    FlexModule,
    MatTableModule,
    MatTabsModule,
  ],
})
export class MaterialModule {}
